name: Deployment pipeline

on:
  push:
   branches:
     - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: E2E tests
        uses: cypress-io/github-action@v2
        with:
          command: npx cypress run
          start: npm run start-test
          wait-on: http://localhost:3000/
     

  